<a href="https://colab.research.google.com/github/DharmikPatel916/CE888/blob/main/Praticals/Week%204/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recommendation Systems

In [1]:
# Loading Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=3)

In [2]:
# Loading data
df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv", header= None)

In [3]:
df.head()

0      1      2      3      4    ...    96     97     98     99     100
0   74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1  100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2   49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3   48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4   91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60

[5 rows x 101 columns]

In [4]:
print(len(df))

24983


In [5]:
orig_df= df
df = df.replace(to_replace=99, value= np.nan)

In [6]:
df.head()

0     1     2     3     4     5    ...   95    96    97    98    99    100
0   74.0 -7.82  8.79 -9.66 -8.16 -7.52  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  100.0  4.08 -0.29  6.36  4.37 -2.38  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   49.0   NaN   NaN   NaN   NaN  9.03  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   48.0   NaN  8.35   NaN   NaN  1.80  ...   NaN   NaN   NaN   NaN   NaN   NaN
4   91.0  8.50  4.61 -4.17 -5.39  1.36  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 101 columns]

In [7]:
df= df.drop(columns=0)
df.head()

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2   NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4  8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60

[5 rows x 100 columns]

In [8]:
ranking = df.rank(axis=1, method='average')

In [9]:
means= df.mean(axis = 0, skipna = True)
#means_=means.values
print(means)

1      0.904573
2      0.208460
3      0.316574
4     -1.449114
5      0.403556
         ...   
96     1.528003
97     1.673750
98     0.767692
99    -0.031244
100    1.354711
Length: 100, dtype: float64


In [10]:
max_index_row = np.argmax(means)
min_index_row = np.argmin(means)
print("Joke no", max_index_row, "has best rating")
print("Joke no", min_index_row, "has worst rating")

Joke no 49 has best rating
Joke no 57 has worst rating


In [11]:
arr= df.values

In [12]:
#rated = np.where(arr!=np.nan)
#print(len(rated[0]), rated[1].shape)

rated = np.where(~np.isnan(arr))
print(len(rated[0]), rated[1].shape)

## rated[0] is the indices for rows and rated[1] is the indices of columns

1810455 (1810455,)


In [13]:
print(len(rated[0]))

1810455


In [14]:
print(len(rated[1]))

1810455


In [15]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(~np.isnan(arr))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [16]:
new_arr, idx = replace(arr, 0.1)

In [17]:
print(new_arr)

[[-7.82 99.   -9.66 ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [  nan   nan   nan ...   nan   nan   nan]
 ...
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]


In [18]:
print(idx)

(array([ 4036,   200, 19650, ..., 18033, 19312,  5565]), array([49, 51, 39, ...,  6, 62,  1]))


In [19]:
print(rated)

(array([    0,     0,     0, ..., 24982, 24982, 24982]), array([ 0,  1,  2, ..., 69, 70, 86]))


In [20]:
arr[idx[0][0], idx[1][0]]

-0.1

In [21]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [22]:
print(new_arr.shape[0])

24983


In [23]:
print(new_arr.shape[1])

100


In [24]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [25]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    
def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating) and rating!=99:
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 5) == 0:
            print('Iteration %d/%d: \t MSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [26]:
num_iter = 50
sgd(num_iter)  # Note how the MSE decreases with the number of iterations

Iteration 0/50: 	 MSE=26.245181
Iteration 5/50: 	 MSE=24.355955
Iteration 10/50: 	 MSE=23.270994
Iteration 15/50: 	 MSE=22.283474
Iteration 20/50: 	 MSE=21.508008
Iteration 25/50: 	 MSE=20.950637
Iteration 30/50: 	 MSE=20.523941
Iteration 35/50: 	 MSE=20.031476
Iteration 40/50: 	 MSE=19.186484
Iteration 45/50: 	 MSE=18.168987


[26.24518136507332,
 24.35595469898589,
 23.270994376638154,
 22.283474469945443,
 21.508007901166668,
 20.950636986497944,
 20.523940790166613,
 20.031475868398502,
 19.186484361046798,
 18.168986927901436]

In [27]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-2.84 , -3.263, -4.179, ..., -1.906, -4.006, -1.552],
       [ 3.371,  3.709,  4.348, ...,  2.858,  4.1  ,  2.794],
       [ 5.223,  5.297,  5.07 , ...,  6.045,  4.572,  6.913],
       ...,
       [ 0.373,  0.416,  0.501, ...,  0.298,  0.475,  0.279],
       [ 0.648,  0.614,  0.469, ...,  0.906,  0.396,  1.107],
       [ 2.39 ,  2.305,  1.881, ...,  3.193,  1.623,  3.846]])

In [29]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [ ]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

1    ...                          100
0      (99.0, -3.4713737999011034)  ...    (nan, -2.180868779993924)
1       (4.08, 3.0882346046596747)  ...     (1.07, 2.84937537120187)
2          (nan, 5.57750022556734)  ...     (nan, 7.253979225328332)
3         (nan, 2.312486200859892)  ...    (nan, 2.9835748580771195)
4        (8.5, 3.2152317802930064)  ...     (1.6, 4.408258301620306)
...                            ...  ...                          ...
24978    (0.44, 2.325966038890644)  ...   (7.43, 3.7867066168261507)
24979    (99.0, 2.529909806656994)  ...   (8.45, 1.9101299902320867)
24980    (nan, -0.806112180006749)  ...   (nan, -0.5756946194871854)
24981   (nan, -1.3075913189460364)  ...  (nan, -0.32692141946874415)
24982    (2.43, 3.168012038825513)  ...     (nan, 4.372994957105565)

[24983 rows x 100 columns]

In [31]:
df.iloc[20073,31]

-6.99

In [32]:
from google.colab import files
uploaded= files.upload()

Saving movies_latent_factors.xlsx to movies_latent_factors.xlsx


In [33]:
import io
users_pref_latentfactors=pd.read_excel(io.BytesIO(uploaded['movies_latent_factors.xlsx']), sheet_name= 'Users' )
items_latentfactor=pd.read_excel(io.BytesIO(uploaded['movies_latent_factors.xlsx']), sheet_name= 'Items' )

In [34]:
users_pref_latentfactors.head(3)

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552

[3 rows x 16 columns]

In [35]:
items_latentfactor.head(3)

Movie ID                                      Title  ...  Factor14  Factor15
0        11  Star Wars: Episode IV - A New Hope (1977)  ...  1.129616 -0.248806
1        12                        Finding Nemo (2003)  ...  0.506876  1.274993
2        13                        Forrest Gump (1994)  ... -2.209004 -0.419092

[3 rows x 17 columns]

In [36]:
Mov_idindex= items_latentfactor['Movie ID'].values
User_idindex= users_pref_latentfactors['User'].values
x= np.where(Mov_idindex == 1572)
items_latentfactor.iloc[x[0],7]

74    0.315561
Name: Factor6, dtype: float64

In [37]:
F13_index= items_latentfactor['Factor13'].values
y= np.where(F13_index == np.min(F13_index))
print(y)

(array([51]),)


In [38]:
users_pref_latentfactors= users_pref_latentfactors.drop(['User'], axis=1)
users_pref_latentfactors.head()

Factor1   Factor2   Factor3  ...  Factor13  Factor14  Factor15
0 -0.204024  0.161079 -0.090447  ...  0.007108 -0.118663 -0.039125
1 -0.189652 -0.178979 -0.091490  ...  0.045916  0.113671  0.179873
2 -0.115308 -0.090886 -0.053129  ...  0.108372  0.054471 -0.109552
3 -0.227462 -0.272532 -0.017231  ...  0.036767 -0.165438  0.050692
4 -0.014616 -0.102218 -0.107935  ... -0.039897  0.129063  0.102669

[5 rows x 15 columns]

In [39]:
items_latentfactor= items_latentfactor.drop(['Movie ID','Title'], axis=1)
items_latentfactor.head()

Factor1   Factor2   Factor3  ...  Factor13  Factor14  Factor15
0 -1.521848 -1.038507  2.027269  ...  0.403861  1.129616 -0.248806
1 -0.342185 -0.296586 -0.385962  ... -0.564415  0.506876  1.274993
2 -2.240888 -0.438815 -2.275177  ... -0.330276 -2.209004 -0.419092
3 -0.634531  2.186059 -0.066681  ... -0.819682  0.549010 -0.681191
4  0.517348 -1.456763  0.369161  ...  1.429191  0.855746 -2.292566

[5 rows x 15 columns]

In [40]:
npusers_pref= users_pref_latentfactors.values
nmitems_lf= items_latentfactor.values

ratings_movie= npusers_pref.dot(nmitems_lf.T)
ratings_df= pd.DataFrame(ratings_movie)
ratings_df.head()

0         1         2   ...        97        98        99
0  0.389174  0.191449  0.766364  ... -0.395129 -0.522412  0.097010
1  0.883069  0.319496  0.396485  ... -0.259385 -0.455462 -0.113381
2  0.214068  0.154537  0.261073  ... -0.083633 -0.163929 -0.199840
3 -0.139366  0.129855  1.212876  ...  0.138995  0.003095 -0.524709
4 -0.038172  0.866052 -0.285316  ...  0.079577  0.070540 -0.357920

[5 rows x 100 columns]

In [41]:
wa=np.where(User_idindex == 3947)
wb=np.where(Mov_idindex == 641)
print(wa, wb)

(array([17]),) (array([55]),)


In [42]:
ratings_df.iloc[wa[0],wb[0]]

55
17  0.133656

In [43]:
ws=np.where(User_idindex == 4373)
print(ws)

(array([18]),)


In [44]:
m_id= pd.DataFrame(Mov_idindex)
new_ratingsdf= pd.concat([ratings_df, m_id.T])
new_ratingsdf.head(10)

0         1         2   ...        97        98        99
0  0.389174  0.191449  0.766364  ... -0.395129 -0.522412  0.097010
1  0.883069  0.319496  0.396485  ... -0.259385 -0.455462 -0.113381
2  0.214068  0.154537  0.261073  ... -0.083633 -0.163929 -0.199840
3 -0.139366  0.129855  1.212876  ...  0.138995  0.003095 -0.524709
4 -0.038172  0.866052 -0.285316  ...  0.079577  0.070540 -0.357920
5  0.063515  0.168541  0.170626  ... -0.161995 -0.125955 -0.183417
6  0.619344  0.396214  0.205784  ... -0.376227 -0.555636  0.193396
7  0.028389  0.017066 -0.025851  ... -0.098649 -0.085649 -0.006351
8  0.033540 -0.066459  0.170744  ... -0.052109 -0.057458 -0.076232
9  0.220284  0.366293 -0.212080  ... -0.105606 -0.104062 -0.445656

[10 rows x 100 columns]

In [45]:
for_sort= new_ratingsdf
for_sort= for_sort.sort_values(by= 18, axis=1)
for_sort.head(10)

5         36        86  ...        35        11        50
0 -0.388917 -0.465304 -1.246529  ...  0.243899  1.075866 -0.194970
1 -0.862520 -0.884860 -1.423655  ...  0.577851  0.510767  1.052255
2  0.447514  0.372406 -0.413831  ...  0.136766  0.045008  0.210838
3 -0.865355 -0.760042 -1.337438  ... -0.101019 -0.075722  1.148704
4 -0.702938 -0.674589 -0.295934  ...  0.511015 -0.211549  0.249057
5  0.072521  0.089879 -0.021397  ... -0.148842 -0.128225 -0.029713
6  0.221597  0.039557 -1.234513  ...  0.817604  0.928983 -0.309976
7  0.012072  0.009027  0.034218  ...  0.037036 -0.039545 -0.008988
8 -0.113526 -0.104043 -0.199980  ... -0.029209 -0.060360  0.029915
9 -0.087702 -0.088447 -0.195774  ...  0.087211 -0.148604  0.725877

[10 rows x 100 columns]